<?php

namespace App\Console\Commands;

use App\Services\Ml\OptimizationService;
use App\Services\Ml\MlServiceUnavailableException;
use App\Models\PurchaseOrder;
use App\Models\PurchaseOrderItem;
use Illuminate\Console\Command;

class OptimizationReplenish extends Command
{
    protected $signature = 'optimization:replenish';

    protected $description = 'Run GA optimization and create draft purchase orders if budget allows';

    public function handle(OptimizationService $optimization): int
    {
        try {
            // Run optimization with default budget
            $result = $optimization->replenishment(['budget' => 10000, 'persist' => false]);

            if (!$result || empty($result['recommendations'])) {
                $this->info('No recommendations generated.');
                return self::SUCCESS;
            }

            $totalOrderValue = $result['total_order_value'] ?? 0;
            $confidence = $result['confidence'] ?? 0;
            $budget = 10000;

            $this->info("Optimization complete: ₱" . number_format($totalOrderValue, 2) . " total order value, " . ($confidence * 100) . "% confidence");

            // Auto-create draft PO if within budget and confidence threshold
            if ($totalOrderValue <= $budget * 0.9 && $confidence >= 0.7) {
                $po = PurchaseOrder::create([
                    'supplier_id' => 1, // Default supplier
                    'status' => 'Draft',
                    'total_amount' => $totalOrderValue,
                    'notes' => 'Auto-generated by optimization pipeline',
                    'created_by' => 'System (ML)',
                ]);

                foreach ($result['recommendations'] as $rec) {
                    PurchaseOrderItem::create([
                        'purchase_order_id' => $po->purchase_order_id,
                        'product_id' => $rec['product_id'],
                        'quantity' => $rec['recommended_quantity'],
                        'unit_cost' => $rec['unit_cost'] ?? 0,
                    ]);
                }

                $this->info("Created draft PO #{$po->purchase_order_id} with " . count($result['recommendations']) . " items");
            } else {
                $this->info("Order value or confidence below threshold — no PO created");
            }

            return self::SUCCESS;
        } catch (MlServiceUnavailableException $e) {
            $this->error("ML service unavailable: {$e->getMessage()}");
            return self::FAILURE;
        } catch (\Exception $e) {
            $this->error("Optimization failed: {$e->getMessage()}");
            return self::FAILURE;
        }
    }
}
