/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#005049",
        "secondary": "#006a61",
        "primary-fixed-dim": "#bec6e0",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#6bd8cb",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#3f465c",
        "tertiary-container": "#271901",
        "on-surface": "#1b1b1d",
        "surface-bright": "#fcf8fa",
        "on-primary-fixed": "#131b2e",
        "on-secondary": "#ffffff",
        "primary-container": "#131b2e",
        "on-tertiary-fixed": "#271901",
        "inverse-surface": "#303032",
        "surface-container-highest": "#e4e2e4",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#dec29a",
        "on-secondary-container": "#006f66",
        "on-primary-container": "#7c839b",
        "surface-tint": "#565e74",
        "on-tertiary-container": "#98805d",
        "on-secondary-fixed": "#00201d",
        "surface-container-lowest": "#ffffff",
        "outline": "#76777d",
        "inverse-primary": "#bec6e0",
        "surface-container-low": "#f6f3f5",
        "inverse-on-surface": "#f3f0f2",
        "surface-variant": "#e4e2e4",
        "on-surface-variant": "#45464d",
        "error": "#ba1a1a",
        "secondary-container": "#86f2e4",
        "primary-fixed": "#dae2fd",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary": "#000000",
        "primary": "#000000",
        "on-background": "#1b1b1d",
        "surface-container-high": "#eae7e9",
        "secondary-fixed": "#89f5e7",
        "outline-variant": "#c6c6cd",
        "background": "#fcf8fa",
        "tertiary-fixed": "#fcdeb5",
        "surface-dim": "#dcd9db",
        "surface": "#fcf8fa",
        "on-tertiary-fixed-variant": "#574425",
        "surface-container": "#f0edef"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xs": "4px",
        "lg": "24px",
        "base": "4px",
        "md": "16px",
        "margin": "24px",
        "gutter": "16px",
        "xl": "32px",
        "sm": "8px",
        "tier-gap": "32px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "unit": "4px"
      },
      fontFamily: {
        "label-md": ["Inter"],
        "headline-lg": ["Inter", "Hanken Grotesk"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-sm": ["Inter"],
        "body-sm": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "display-lg": ["Inter", "Hanken Grotesk"],
        "tabular-nums": ["Inter"],
        "pricing-number": ["Hanken Grotesk"],
        "currency-symbol": ["Inter"],
        "headline-xl": ["Hanken Grotesk"],
        "label-caps": ["JetBrains Mono"]
      },
      fontSize: {
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "tabular-nums": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "pricing-number": ["40px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "currency-symbol": ["24px", { "lineHeight": "32px", "fontWeight": "500" }],
        "headline-xl": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "16px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}