<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * The failed-job ledger.
 *
 * Laravel writes here once a job has exhausted `$tries`, so operators can inspect
 * and retry it (`php artisan queue:retry --all`) instead of it vanishing into the
 * queue's own logs. Generated by `php artisan queue:failed-table`.
 */
return new class extends Migration
{
    public function up(): void
    {
        // The table can already exist on databases that were bootstrapped with
        // `php artisan queue:failed-table` before this migration existed.
        if (Schema::hasTable('failed_jobs')) {
            return;
        }

        Schema::create('failed_jobs', function (Blueprint $table) {
            $table->id();
            $table->string('uuid')->unique();
            $table->text('connection');
            $table->text('queue');
            $table->longText('payload');
            $table->longText('exception');
            $table->timestamp('failed_at')->useCurrent();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('failed_jobs');
    }
};
